import formsPlugin from '@tailwindcss/forms';
import typographyPlugin from '@tailwindcss/typography';

/** @type {import('tailwindcss').Config} */
export default {
  content: ['./app/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: 'rgb(var(--color-primary) / <alpha-value>)',
        contrast: 'rgb(var(--color-contrast) / <alpha-value>)',
        notice: 'rgb(var(--color-accent) / <alpha-value>)',
        shopPay: 'rgb(var(--color-shop-pay) / <alpha-value>)',
      },
      screens: {
        small:'24em',
        sm: '32em',
        md: '48em',
        tab: '60em',
        lg: '70em',
        zx: '25em',
        xc:'111.25em',
        xl: '80em',
        '2xl': '84em',
        '3xl': '134em',
        'sm-max': {max: '48em'},
        'sm-only': {min: '32em', max: '48em'},
        'md-only': {min: '48em', max: '64em'},
        'lg-only': {min: '64em', max: '80em'},
        'xl-only': {min: '80em', max: '96em'},
        '2xl-only': {min: '96em'},
        'max-lg': {max: '1279px'},
        'max-sm': {max: '749px'}
      },
      spacing: {
        nav: 'var(--height-nav)',
        screen: 'var(--screen-height, 100vh)',
      },
      height: {
        screen: 'var(--screen-height, 100vh)',
        'screen-no-nav':
          'calc(var(--screen-height, 100vh) - var(--height-nav))',
        'screen-dynamic': 'var(--screen-height-dynamic, 100vh)',
      },
      width: {
        mobileGallery: 'calc(100vw - 3rem)',
      },
      fontFamily: {
        sans: ['Helvetica Neue', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        serif: ['"IBMPlexSerif"', 'Palatino', 'ui-serif'],
        tarzan: ['Tarzan'],
        stitch: ['Stitch'],
        pinocchio: ['Pinocchio'],
        simba: ['Simba'],
        roo: ['Roo'],
        nimo: ['Nimo'],
        lumiere: ['Lumiere'],
        kaa: ['Kaa'],
        kaaNew: ['Kaa-new'],
        dumbo: ['Dumbo'],
        donald: ['Donald'],
        aladdin: ['Aladdin'],
        belle: ['Belle'],
        boo: ['Boo'],
        cinderella: ['Cinderella'],
        copper: ['Copper'],
        jasmine: ['Jasmine'],
        merlin: ['Merlin'],
        goofy: ['Goofy'],
        hercules: ['Hercules'],
        rafiki: ['Rafiki'],
        rapunzel: ['Rapunzel'],
        sarabi: ['Sarabi'],
        scar: ['Scar'],
        triton: ['Triton'],
        woody: ['Woody'],
        ratigan: ['Ratigan'],
        beauty: ['Beauty'],
        karla: ['Karla'],
        'hello keta': ['hello keta'],
        'sea garden': ['sea garden'],
        'great vibes': ['great vibes'],
        'Copper Canyon': ['Copper Canyon'],
        Alex: ['Alex'],
        wedding: ['wedding'],
        Via: ['Via'],
        'Winter Song': ['Winter Song'],
        'Premium Ultra': ['Premium Ultra'],
        dente: ['Al-dente'],
        arial: ['Arial'],
        'comic sans ms': ['Comic Sans MS']
      },
      fontSize: {
        display: ['var(--font-size-display)', '1.1'],
        heading: ['var(--font-size-heading)', '1.25'],
        lead: ['var(--font-size-lead)', '1.333'],
        copy: ['var(--font-size-copy)', '1.5'],
        fine: ['var(--font-size-fine)', '1.333'],
      },
      maxWidth: {
        'prose-narrow': '45ch',
        'prose-wide': '80ch',
      },
      boxShadow: {
        border: 'inset 0px 0px 0px 1px rgb(var(--color-primary) / 0.08)',
        darkHeader: 'inset 0px -1px 0px 0px rgba(21, 21, 21, 0.4)',
        lightHeader: 'inset 0px -1px 0px 0px rgba(21, 21, 21, 0.05)',
        box:'0 15px 15px 5px rgba(245, 246, 240, 0.39)',
        shbox:'0 15px 15px 5px rgba(245, 246, 240, 0.59)'
      },
    },
  },
  plugins: [formsPlugin, typographyPlugin],
};
